# Generated by Django 5.2.4 on 2025-08-13 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="bloguser",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="last modify time",
            ),
        ),
        migrations.AlterField(
            model_name="bloguser",
            name="nickname",
            field=models.CharField(
                blank=True,
                db_comment="用户昵称，可为空",
                max_length=100,
                verbose_name="nick name",
            ),
        ),
        migrations.AlterField(
            model_name="bloguser",
            name="source",
            field=models.CharField(
                blank=True,
                db_comment="用户创建来源，如注册/导入/第三方绑定",
                max_length=100,
                verbose_name="create source",
            ),
        ),
    ]
