# Generated by Django 5.2.4 on 2025-08-13 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owntracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owntracklog",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="记录创建时间",
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
        ),
        migrations.AlterField(
            model_name="owntracklog",
            name="lat",
            field=models.FloatField(db_comment="纬度坐标", verbose_name="纬度"),
        ),
        migrations.AlterField(
            model_name="owntracklog",
            name="lon",
            field=models.FloatField(db_comment="经度坐标", verbose_name="经度"),
        ),
        migrations.AlterField(
            model_name="owntracklog",
            name="tid",
            field=models.CharField(
                db_comment="终端/用户标识", max_length=100, verbose_name="用户"
            ),
        ),
    ]
