# Generated by Django 5.2.4 on 2025-08-13 17:48

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_order",
            field=models.IntegerField(
                db_comment="文章排序（数值越大越靠前）", default=0, verbose_name="order"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                db_comment="作者（关联用户）",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=mdeditor.fields.MDTextField(
                db_comment="文章正文（Markdown）", verbose_name="body"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                db_comment="所属分类",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="comment_status",
            field=models.CharField(
                choices=[("o", "Open"), ("c", "Close")],
                db_comment="评论状态：o=开放，c=关闭",
                default="o",
                max_length=1,
                verbose_name="comment status",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(
                db_comment="主键ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="modify time",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_time",
            field=models.DateTimeField(
                db_comment="发布时间",
                default=django.utils.timezone.now,
                verbose_name="publish time",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="show_toc",
            field=models.BooleanField(
                db_comment="是否显示目录（TOC）", default=False, verbose_name="show toc"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("d", "Draft"), ("p", "Published")],
                db_comment="发布状态：d=草稿，p=已发布",
                default="p",
                max_length=1,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                db_comment="文章标题，要求唯一",
                max_length=200,
                unique=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[("a", "Article"), ("p", "Page")],
                db_comment="类型：a=文章，p=页面",
                default="a",
                max_length=1,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(
                db_comment="浏览次数", default=0, verbose_name="views"
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="analytics_code",
            field=models.TextField(
                db_comment="统计/分析代码",
                default="",
                max_length=1000,
                verbose_name="网站统计代码",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="article_comment_count",
            field=models.IntegerField(
                db_comment="文章页评论分页大小",
                default=5,
                verbose_name="article comment count",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="article_sub_length",
            field=models.IntegerField(
                db_comment="文章摘要长度（字符数）",
                default=300,
                verbose_name="article sub length",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="beian_code",
            field=models.CharField(
                blank=True,
                db_comment="工信部备案号",
                default="",
                max_length=2000,
                null=True,
                verbose_name="备案号",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="comment_need_review",
            field=models.BooleanField(
                db_comment="评论是否需要人工审核",
                default=False,
                verbose_name="评论是否需要审核",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="global_footer",
            field=models.TextField(
                blank=True,
                db_comment="全站公共 HTML 尾部代码",
                default="",
                null=True,
                verbose_name="公共尾部",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="global_header",
            field=models.TextField(
                blank=True,
                db_comment="全站公共 HTML 头部代码",
                default="",
                null=True,
                verbose_name="公共头部",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="gongan_beiancode",
            field=models.TextField(
                blank=True,
                db_comment="公安备案号",
                default="",
                max_length=2000,
                null=True,
                verbose_name="公安备案号",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="google_adsense_codes",
            field=models.TextField(
                blank=True,
                db_comment="AdSense 代码片段",
                default="",
                max_length=2000,
                null=True,
                verbose_name="adsense code",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="open_site_comment",
            field=models.BooleanField(
                db_comment="全站是否开启评论",
                default=True,
                verbose_name="open site comment",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="show_gongan_code",
            field=models.BooleanField(
                db_comment="是否显示公安备案信息",
                default=False,
                verbose_name="是否显示公安备案号",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="show_google_adsense",
            field=models.BooleanField(
                db_comment="是否显示 Google AdSense",
                default=False,
                verbose_name="show adsense",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="sidebar_article_count",
            field=models.IntegerField(
                db_comment="侧边栏文章数量",
                default=10,
                verbose_name="sidebar article count",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="sidebar_comment_count",
            field=models.IntegerField(
                db_comment="侧边栏评论数量",
                default=5,
                verbose_name="sidebar comment count",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="site_description",
            field=models.TextField(
                db_comment="站点描述",
                default="",
                max_length=1000,
                verbose_name="site description",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="site_keywords",
            field=models.TextField(
                db_comment="站点关键词",
                default="",
                max_length=1000,
                verbose_name="site keywords",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="site_name",
            field=models.CharField(
                db_comment="站点名称",
                default="",
                max_length=200,
                verbose_name="site name",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="site_seo_description",
            field=models.TextField(
                db_comment="SEO 描述",
                default="",
                max_length=1000,
                verbose_name="site seo description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                db_comment="主键ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="index",
            field=models.IntegerField(
                db_comment="排序权重（越大越靠前）", default=0, verbose_name="index"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="modify time",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_comment="分类名称，要求唯一",
                max_length=30,
                unique=True,
                verbose_name="category name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                db_comment="父级分类",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
                verbose_name="parent category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_comment="URL 友好名（自动生成）",
                default="no-slug",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="is_enable",
            field=models.BooleanField(
                db_comment="是否启用显示", default=True, verbose_name="is show"
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="last_mod_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="modify time",
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="link",
            field=models.URLField(
                db_comment="友情链接地址（URL）", verbose_name="link"
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="name",
            field=models.CharField(
                db_comment="友情链接名称，要求唯一",
                max_length=30,
                unique=True,
                verbose_name="link name",
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="sequence",
            field=models.IntegerField(
                db_comment="显示顺序，数值越小越靠前", unique=True, verbose_name="order"
            ),
        ),
        migrations.AlterField(
            model_name="links",
            name="show_type",
            field=models.CharField(
                choices=[
                    ("i", "index"),
                    ("l", "list"),
                    ("p", "post"),
                    ("a", "all"),
                    ("s", "slide"),
                ],
                db_comment="展示位置：i=首页，l=列表页，p=文章页，a=全部，s=幻灯片",
                default="i",
                max_length=1,
                verbose_name="show type",
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="content",
            field=models.TextField(
                db_comment="侧边栏内容（支持 HTML）", verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="is_enable",
            field=models.BooleanField(
                db_comment="是否启用显示", default=True, verbose_name="is enable"
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="last_mod_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="modify time",
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="name",
            field=models.CharField(
                db_comment="侧边栏标题", max_length=100, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="sidebar",
            name="sequence",
            field=models.IntegerField(
                db_comment="显示顺序，数值越小越靠前", unique=True, verbose_name="order"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(
                db_comment="主键ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="modify time",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                db_comment="标签名称，要求唯一",
                max_length=30,
                unique=True,
                verbose_name="tag name",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                blank=True,
                db_comment="URL 友好名（自动生成）",
                default="no-slug",
                max_length=60,
            ),
        ),
    ]
