# Generated by Django 5.2.4 on 2025-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_article_article_order_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.CharField(
                blank=True,
                db_comment="文章摘要，可为空",
                max_length=500,
                null=True,
                verbose_name="summary",
            ),
        ),
    ]
