# Generated by Django 5.2.4 on 2025-08-13 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_article_article_order_alter_article_author_and_more"),
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                db_comment="所属文章",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.article",
                verbose_name="article",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                db_comment="评论作者",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(
                db_comment="评论正文，最多300字符", max_length=300, verbose_name="正文"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_enable",
            field=models.BooleanField(
                db_comment="是否已启用/审核通过", default=False, verbose_name="enable"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="last modify time",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                db_comment="父级评论（用于楼中楼）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.comment",
                verbose_name="parent comment",
            ),
        ),
    ]
