# Generated by Django 5.2.4 on 2025-08-13 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthconfig",
            name="appkey",
            field=models.CharField(
                db_comment="第三方平台 AppKey/ClientID",
                max_length=200,
                verbose_name="AppKey",
            ),
        ),
        migrations.AlterField(
            model_name="oauthconfig",
            name="appsecret",
            field=models.CharField(
                db_comment="第三方平台 AppSecret/ClientSecret",
                max_length=200,
                verbose_name="AppSecret",
            ),
        ),
        migrations.AlterField(
            model_name="oauthconfig",
            name="callback_url",
            field=models.CharField(
                db_comment="回调地址",
                default="",
                max_length=200,
                verbose_name="callback url",
            ),
        ),
        migrations.AlterField(
            model_name="oauthconfig",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="oauthconfig",
            name="is_enable",
            field=models.BooleanField(
                db_comment="是否启用该平台登录", default=True, verbose_name="is enable"
            ),
        ),
        migrations.AlterField(
            model_name="oauthconfig",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="last modify time",
            ),
        ),
        migrations.AlterField(
            model_name="oauthconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("weibo", "weibo"),
                    ("google", "google"),
                    ("github", "GitHub"),
                    ("facebook", "FaceBook"),
                    ("qq", "QQ"),
                ],
                db_comment="配置类型（平台标识）",
                default="a",
                max_length=10,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_comment="关联站内用户（可为空）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="creation_time",
            field=models.DateTimeField(
                db_comment="创建时间",
                default=django.utils.timezone.now,
                verbose_name="creation time",
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="email",
            field=models.CharField(
                blank=True,
                db_comment="邮箱（可能由第三方返回）",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="last_modify_time",
            field=models.DateTimeField(
                db_comment="最后修改时间",
                default=django.utils.timezone.now,
                verbose_name="last modify time",
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="metadata",
            field=models.TextField(
                blank=True, db_comment="第三方原始数据（JSON/文本）", null=True
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="nickname",
            field=models.CharField(
                db_comment="第三方昵称", max_length=50, verbose_name="nick name"
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="openid",
            field=models.CharField(
                db_comment="第三方平台用户唯一标识 openid", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="picture",
            field=models.CharField(
                blank=True, db_comment="头像 URL", max_length=350, null=True
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="token",
            field=models.CharField(
                blank=True,
                db_comment="访问令牌/刷新令牌等信息",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="oauthuser",
            name="type",
            field=models.CharField(
                db_comment="第三方平台类型，如 github/google/qq 等", max_length=50
            ),
        ),
    ]
