# Generated by Django 5.2.4 on 2025-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servermanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Commands",
            name="command",
            field=models.CharField(
                db_comment="命令内容/脚本", max_length=2000, verbose_name="命令"
            ),
        ),
        migrations.AlterField(
            model_name="Commands",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="Commands",
            name="describe",
            field=models.CharField(
                db_comment="命令用途或备注说明", max_length=300, verbose_name="命令描述"
            ),
        ),
        migrations.AlterField(
            model_name="Commands",
            name="last_modify_time",
            field=models.DateTimeField(
                auto_now=True, db_comment="最后修改时间", verbose_name="修改时间"
            ),
        ),
        migrations.AlterField(
            model_name="Commands",
            name="title",
            field=models.CharField(
                db_comment="命令的简短标题", max_length=300, verbose_name="命令标题"
            ),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="content",
            field=models.TextField(db_comment="邮件内容正文", verbose_name="邮件内容"),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="emailto",
            field=models.CharField(
                db_comment="收件人邮箱（可多邮箱分隔）",
                max_length=300,
                verbose_name="收件人",
            ),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="send_result",
            field=models.BooleanField(
                db_comment="发送结果：True=成功，False=失败",
                default=False,
                verbose_name="结果",
            ),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="title",
            field=models.CharField(
                db_comment="邮件标题", max_length=2000, verbose_name="邮件标题"
            ),
        ),
    ]
